# 默认处理的文件或目录,以'':''开关，或路径中包含'':''的，视为绝对路径
source:
  # 目录路径或文件路径
  value:
    - ./source
  # 编码格式(如果需要)
  encoding: utf-8
  # 文件扩展名
  ext_name:
    - xlsx

# 输出目录,以'':''开关，或路径中包含'':''的，视为绝对路径,
# encoding属性作用于字符文件的输出,和字节文件中字符串的编码
target:
  # 输出目录
  root: ./target
  # 定义目录
  title:
    client: titles/client
    server: titles/server
    db: titles/db
  # 数据目录
  data:
    client: data/client
    server: data/server
    db: data/db
  # 常量目录
  const:
    client: const/client
    server: const/server
  # 编码格式(暂时不支持修改)
  encoding : utf-8

# 缓冲区定义
buff:
  # 数据导出是否使用高位在前
  big_endian: true
  # 每个token的最大缓冲区
  token: 512
  # 每个item的最大缓冲区
  item: 2048
  # 每个sheet的最大缓冲区
  sheet: 2096000

